sudo: required
language: generic
services:
  - docker
script:
  - docker build -t lexicoder/mssql-with-agent:latest . | tee /dev/tty | grep 'mssql-server amd64' > version
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - version=$(< version) && version_array=($version) && export version_number=${version_array[6]}
  - docker tag lexicoder/mssql-with-agent:latest lexicoder/mssql-with-agent:$version_number
  - docker push lexicoder/mssql-with-agent
